Repository Me1tingPot/FE, pull requests merged in 2024-05, with the labels that each got.

#1 [#1] i18next 타입 추가
  src/hooks/queries/useAuth.ts
  src/hooks/useModal.ts
  src/locales/i18n.config.ts
  src/screens/my/MyHomeScreen.tsx
  src/types/i18next.d.ts
Labels: enhancement

#5 Feat: signUp screen 구현
  .gitignore
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/fonts/Pretendard-Bold.otf
  android/app/src/main/assets/fonts/Pretendard-ExtraLight.otf
  android/app/src/main/assets/fonts/Pretendard-Light.otf
  android/app/src/main/assets/fonts/Pretendard-Medium.otf
  android/app/src/main/assets/fonts/Pretendard-Regular.otf
  android/link-assets-manifest.json
  ios/MeltingPot.xcodeproj/project.pbxproj
  ios/MeltingPot/Info.plist
  ios/Podfile
  ios/Podfile.lock
  ios/link-assets-manifest.json
  package.json
  react-native.config.js
  src/assets/fonts/Pretendard-Bold.otf
  src/assets/fonts/Pretendard-ExtraLight.otf
  src/assets/fonts/Pretendard-Light.otf
  src/assets/fonts/Pretendard-Medium.otf
  src/assets/fonts/Pretendard-Regular.otf
  src/components/common/CompoundOption.tsx
  src/components/common/CustomTextInput.tsx
  src/components/form/GenericForm.tsx
  src/components/signup/Birth.tsx
  src/components/signup/CameraOrLibrary.tsx
  src/components/signup/DatePickerOption.tsx
  src/components/signup/Email.tsx
  src/components/signup/FaceImg.tsx
  src/components/signup/Finish.tsx
  src/components/signup/Language.tsx
  src/components/signup/Location.tsx
  src/components/signup/Name.tsx
  src/components/signup/Password.tsx
  src/components/signup/Sex.tsx
  src/components/signup/index.ts
  src/constants/index.ts
  src/constants/messages.ts
  src/constants/navigations.ts
  src/hooks/usePermission.ts
  src/locales/translations/en.json
  src/locales/translations/ko.json
  src/navigations/stack/AuthStackNavigator.tsx
  src/screens/auth/AuthHomeScreen.tsx
  src/screens/auth/SignUpFinishScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/utils/date.ts
  src/utils/index.ts
Labels: Feat

#4 feat: FeedMain Screen 구현
  .gitignore
  src/assets/Logo.png
  src/components/common/HeaderButton.tsx
  src/components/common/SearchInput.tsx
  src/components/feed/FeedHomeBox.tsx
  src/components/feed/FeedHomeHeaderLeft.tsx
  src/constants/colors.ts
  src/navigations/tab/FeedTabNavigator.tsx
  src/screens/feed/FeedHomeScreen.tsx
Labels: Feat

#6 Feature/#6 WishListPage 구현
  App.tsx
  package.json
  src/components/calendar/Calendar.tsx
  src/components/calendar/DateBox.tsx
  src/components/calendar/DayOfWeeks.tsx
  src/components/calendar/YearSelector.tsx
  src/components/common/CompoundCard.tsx
  src/components/common/CustomButton.tsx
  src/components/common/HeaderButton.tsx
  src/components/common/PartyCard.tsx
  src/components/feed/FeedHomeBox.tsx
  src/components/feed/FeedHomeHeaderLeft.tsx
  src/components/signup/Location.tsx
  src/components/wish/ReservationPartyList.tsx
  src/constants/index.ts
  src/constants/navigations.ts
  src/constants/numbers.ts
  src/locales/translations/en.json
  src/locales/translations/ko.json
  src/navigations/root/RootNavigator.tsx
  src/navigations/stack/AuthStackNavigator.tsx
  src/navigations/tab/FeedTabNavigator.tsx
  src/navigations/topTab/WishTopTabNavigator.tsx
  src/screens/auth/AuthHomeScreen.tsx
  src/screens/party/PartyHomeScreen.tsx
  src/screens/wish/WishReservationScreen.tsx
  src/screens/wish/WishSaveScreen.tsx
  src/utils/date.ts
Labels: Feat

#9 Feature/#7
  @types/global/index.d.ts
  src/assets/images/Comment.png
  src/assets/images/InThePot.png
  src/assets/images/Report.png
  src/components/community/PostPreview.tsx
  src/components/signup/Birth.tsx
  src/components/signup/Location.tsx
  src/components/signup/Name.tsx
  src/screens/auth/SignUpFinishScreen.tsx
  src/screens/community/CommunityHomeScreen.tsx
Labels: Feat

#10 Feature/#9 FireBase 설정 & Community Screen 구현
  App.tsx
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  index.js
  ios/GoogleService-Info.plist
  ios/MeltingPot.xcodeproj/project.pbxproj
  ios/MeltingPot/AppDelegate.mm
  ios/MeltingPot/Info.plist
  ios/MeltingPot/PrivacyInfo.xcprivacy
  ios/Podfile
  package.json
  src/components/community/MultipleGradientBgTextInput.tsx
  src/components/community/PostPreview.tsx
  src/constants/navigations.ts
  src/locales/translations/en.json
  src/locales/translations/ko.json
  src/navigations/stack/CommunityStackNavigator.tsx
  src/navigations/tab/FeedTabNavigator.tsx
  src/navigations/topTab/CommunityTopTabNavigator.tsx
  src/screens/community/CommunityPostingDetailScreen.tsx
  src/screens/community/CommunityPostingScreen.tsx
  src/screens/community/CommunityQuestionScreen.tsx
Labels: Feat

#15 REVERT: 브랜치 복구
  src/assets/Logo.png
  src/components/common/BottomButton.tsx
  src/components/common/CompoundCard.tsx
  src/components/common/PartyCard.tsx
  src/components/my/ChangeLanguageOption.tsx
  src/components/my/DarkModeOption.tsx
  src/components/my/SettingItem.tsx
  src/constants/navigations.ts
  src/locales/translations/en.json
  src/locales/translations/ko.json
  src/navigations/stack/MyStackNavigator.tsx
  src/navigations/tab/FeedTabNavigator.tsx
  src/screens/feed/FeedHomeScreen.tsx
  src/screens/my/MyEditProfileScreen.tsx
  src/screens/my/MyHomeScreen.tsx
  src/screens/my/MyWritePostScreen.tsx
  src/screens/wish/WishHomeScreen.tsx
  src/screens/wish/WishSaveScreen.tsx
Labels: bug

#17 Feature/#12 Firebase 설정
  App.tsx
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  index.js
  ios/GoogleService-Info.plist
  ios/MeltingPot.xcodeproj/project.pbxproj
  ios/MeltingPot/AppDelegate.mm
  ios/MeltingPot/PrivacyInfo.xcprivacy
  ios/Podfile
  package.json
Labels: Feat

#18 Feature/#13: Swipable Party Card 컴포넌트, IconCircleButton 컴포넌트 유연한 수정.
  App.tsx
  src/components/common/CompoundCard.tsx
  src/components/common/IconCircleButton.tsx
  src/components/common/PartyCard.tsx
  src/screens/auth/AuthHomeScreen.tsx
  src/screens/community/CommunityPostingDetailScreen.tsx
  src/screens/community/CommunityQuestionScreen.tsx
  src/screens/feed/FeedHomeScreen.tsx
  src/screens/my/MyHomeScreen.tsx
Labels: Feat
